# Generated by Django 5.2 on 2025-04-08 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAssiduidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.TimeField()),
                ('saida', models.TimeField()),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcionario')),
            ],
        ),
    ]
