# Generated by Django 5.1.6 on 2025-04-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_registroassiduidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='Nivel_academico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='Situacao_actual',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='funcionarios/documentos/'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='formacao_Profissional',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('efetivo', 'Efetivo'), ('temporario', 'Temporário'), ('estagio', 'Estágio')], max_length=10, null=True),
        ),
    ]
