# Generated by Django 5.2 on 2025-04-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_funcionario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='bi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='iban',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nss',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='Situacao_actual',
            field=models.CharField(choices=[('activo', 'Ativo'), ('inactivo', 'Inativo')], default='activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='funcionarios/fotos/'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efetivo'), ('temporario', 'Temporário'), ('estagio', 'Estágio')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='RegistroAssiduidade',
        ),
    ]
