# Generated by Django 5.2 on 2025-04-12 04:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_data_nascimento_funcionario_data_nascimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='documento',
        ),
        migrations.CreateModel(
            name='Assiduidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.TimeField()),
                ('saida', models.TimeField(blank=True, null=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('duracao', models.DurationField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assiduidade', to='app.funcionario')),
            ],
        ),
    ]
