# Generated by Django 5.2 on 2025-04-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_funcionario_bi_funcionario_iban_funcionario_nss_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='data_nascimento',
            new_name='data_Nascimento',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='Estado_Civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro'), ('casado', 'Casado')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='Genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10, null=True),
        ),
    ]
