# Generated by Django 5.2 on 2025-04-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_employees', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('permissions', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='assiduidade',
            name='funcionario',
        ),
        migrations.DeleteModel(
            name='OTPCode',
        ),
        migrations.DeleteModel(
            name='Assiduidade',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
