# Generated by Django 5.2 on 2025-04-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customfield_department_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='type',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Data'), ('email', 'Email'), ('select', 'Seleção'), ('checkbox', 'Checkbox')], default='text', max_length=20),
        ),
    ]
