# Generated by Django 5.2 on 2025-04-26 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_funcionario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'verbose_name': 'Campo Personalizado', 'verbose_name_plural': 'Campos Personalizados'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AddField(
            model_name='customfield',
            name='options',
            field=models.JSONField(blank=True, help_text='Para tipo "Seleção", informe as opções em formato JSON', null=True, verbose_name='Opções'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.role', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Rótulo'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(help_text='Usar snake_case (ex: data_nascimento)', max_length=255, unique=True, verbose_name='Nome Técnico'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Obrigatório'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='type',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Data'), ('select', 'Seleção'), ('checkbox', 'Checkbox')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='department',
            name='max_employees',
            field=models.PositiveIntegerField(blank=True, help_text='Deixe em branco para ilimitado', null=True, verbose_name='Máximo de Funcionários'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dados_personalizados',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dados Personalizados'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(default=list, verbose_name='Permissões'),
        ),
    ]
